jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node6:
        NODE_VERSION: '6.x'
      Node8:
        NODE_VERSION: '8.x'
      Node10:
        NODE_VERSION: '10.x'

  steps:
  - task: PowerShell@0
    inputs:
      script: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
    displayName: 'Update Node.js'

  - script: |
      npm install -g npm
      npm install
    displayName: 'npm install'
    
  - script: |
      node --version
      npm --version
      npm test
    displayName: 'Test'
