jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Node6:
        NODE_VERSION: '6.x'
      Node8:
        NODE_VERSION: '8.x'
      Node10:
        NODE_VERSION: '10.x'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
      checkLatest: true
    displayName: 'Update Node.js'

  - script: |
      npm install -g npm
      npm install
    displayName: 'npm install'
    
  - script: |
      node --version
      npm --version
    displayName: 'Print versions'
    
  - script: |
      npm install mocha
      mocha test/index.js
    displayName: 'Test'    
